# Goal: To deploy the built images from CI Steps once the CI Worklow is Succeeded
name: CD

on:
  workflow_call: 
jobs:
  deploy:
    runs-on: ip-10-0-0-112
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy Example Env to main env
        run: cp .env.example .env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Deploy with Docker Compose
        run: |
          docker compose pull   # ensures latest images
          docker compose up -d --force-recreate
